name: Provision and Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Infrastructure using Bicep template
      - name: Deploy Bicep template
        uses: azure/CLI@v1
        id: deploy-infra  # Add an ID for capturing output
        with:
          inlineScript: |
            az deployment group create \
              --resource-group TechSolutionsRG \
              --name deployVidSpot \
              --template-file ./bicep/main.bicep \
              --parameters randomSeed=${{ github.run_id }}
            az deployment group show \
              --resource-group TechSolutionsRG \
              --name deployVidSpot \
              --query "properties.outputs" > outputs.json

      # Step 4: Extract Web App Names
      - name: Parse Output Variables
        run: |
          WEBAPP_CI=$(jq -r '.webAppNameCentralIndia.value' outputs.json)
          WEBAPP_SEA=$(jq -r '.webAppNameSoutheastAsia.value')
          echo "WEBAPP_CI=$WEBAPP_CI" >> $GITHUB_ENV
          echo "WEBAPP_SEA=$WEBAPP_SEA" >> $GITHUB_ENV

      # Step 5: Deploy Application Code to Central India Web App
      - name: Deploy Application Code to Web App (Central India)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name $WEBAPP_CI \
              --resource-group TechSolutionsRG \
              --src-path ./src/publish \
              --type zip

      # Step 6: Deploy Application Code to Southeast Asia Web App
      - name: Deploy Application Code to Web App (Southeast Asia)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name $WEBAPP_SEA \
              --resource-group TechSolutionsRG \
              --src-path ./src/publish \
              --type zip
