name: Provision and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Infrastructure using Bicep template
      - name: Deploy Bicep template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group TechSolutionsRG \
              --template-file ./bicep/main.bicep

      # Step 4: Deploy Application Code to Central India Web App
      - name: Deploy Application Code to Web App (Central India)
        uses: azure/webapps-deploy@v2
        with:
          app-name: TechSolutionsWebAppCentralIndia
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CENTRAL_INDIA }}
          package: ./src/publish

      # Step 5: Deploy Application Code to Southeast Asia Web App
      - name: Deploy Application Code to Web App (Southeast Asia)
        uses: azure/webapps-deploy@v2
        with:
          app-name: TechSolutionsWebAppSoutheastAsia
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SOUTHEAST_ASIA }}
          package: ./src/publish
